### ISSUE TITLE
Can this be used with Artemis boards?

### ISSUE THREAD

**Issue by Merlin04** [sparkfun/SparkFun_Edge_BSP#10]
I'm wondering if this can be used with Artemis boards. All the examples seem to use Edge board specific hardware, but they both use the same processor. What changes do I need to make (if any) to make this work with the Artemis boards?

**Comment by oclyke** [comment]
@Merlin04, generally speaking yes it is possible. Let me quickly explain what the BSP is for:

The BSP has two main purposes:

1. Provide human-readable names for pins, busses, and other board-specific hardware
1. Provide some standardized functions that may be used across many examples (such as all the examples in the Apollo3 EVB directory).

Long story short you can mix and match different BSPs (for example compiling with the AP3EVB BSP but uploading to Edge) but you will likely have to make some small changes to pin numbers and the printf linking. 

You can also generate your own BSP for a given board by using the tools from the AmbiqSuite SDK. Check out ```{SDK_ROOT}/tools/bsp_generator/pinconfig.py``` which you supply with a 'bsp_pins.src' file to produce 'am_bsp_pins.h' and 'am_bsp_pins.c'

You may also want to customize 'am_bsp.h' and 'am_bsp.c' to provide proper function definitions for things like:

- void am_bsp_low_power_init(void);
- void am_bsp_debug_printf_enable(void);
- void am_bsp_debug_printf_disable(void);

**Comment by Merlin04** [comment]
Could I see an example `bsp_pins.src` file for the Edge board so I can adapt it to the Artemis Nano? I'm not sure what the format of that file should be.

**Comment by Merlin04** [comment]
Never mind, I found the file in the repository. Can the functions that you mentioned stay the same as they were for the edge board?

**Comment by oclyke** [comment]
Yes for the most part. If something is misbehaving it would be worth a second look in that area.

Be aware that we have not updated this BSP in a while now and when we first created it we weren't as familiar with the Ambiq SDK as we are now.

**Comment by Merlin04** [comment]
Ok. One last question, what is this for:
```
pin
    name            = UART_CTS
    pinnum          = 45
    func_sel        = AM_HAL_PIN_45_UART1CTS

pin
    name            = UART_RTS
    pinnum          = 44
    func_sel        = AM_HAL_PIN_44_UART1RTS
    drvstrength     = 2
```
I looked at the Edge board schematic and I don't see anything related to cts or rts. Should I just remove it?

**Comment by oclyke** [comment]
Sure - those pins do not exist on the Edge board. By removing them it is possible that you'll have compilation errors on a select few examples (from the AP3EVB) but that's probably a good thing because it alerts you to the discrepancy.

**Comment by Merlin04** [comment]
Now that I've looked at it more, turns out that I have another question. I'm a bit confused about all of the other sections (IOM, IOS, ITM, etc), probably because I've never looked at the Apollo3 datasheet until today. Do I have to change those?

**Comment by oclyke** [comment]
I would leave those as they are -- currently those cover all the IOMaster, IOSlave, and other peripherals. The BSP just provides nice names for these things -- it doesn't mean you have to use them or enable them.

**Comment by ComputerAided** [comment]
I was trying to flash the Edge BSP Project Template to the Artemis ATP, and it looks like the code is compiling fine, but I am having troubles uploading on Ubuntu 18.04 LTS. I followed the instructions in the Edge tutorial, except for the fact that I needed to use version 2.1.0 of the SDK since I can no longer access version 2.0.0 that was given in the tutorial. In order to let everything compile, I also needed to change permissions of the python files to 755 in `$(SKROOT)/tools/apollo3_scripts/`. Additionally, I needed to add myself to dialout.

Running `make` compiles everything successfully, but when I run the `make bootload` command, the uart_wired_update_sparkfun.py module fails with the following error:
```bash
/home/***/AmbiqSuite-Rel2.1.0/boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py -b 921600 /dev/ttyUSB0  -r 1 -f bin/main_nonsecure_wire.bin -i 6
Connecting with Corvette over serial port /dev/ttyUSB0...
Sending Hello.
No response for command 0x00000000
received bytes  3
['0x0', '0x0', '0x0']
Traceback (most recent call last):
  File "/home/***/AmbiqSuite-Rel2.1.0/boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py", line 341, in <module>
    main()
  File "/home/***/AmbiqSuite-Rel2.1.0/boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py", line 42, in main
    connect_device(ser)
  File "/home/***/AmbiqSuite-Rel2.1.0/boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py", line 61, in connect_device
    response = send_command(hello, 88, ser)
  File "/home/***/AmbiqSuite-Rel2.1.0/boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py", line 238, in send_command
    raise NoResponseError
__main__.NoResponseError
Makefile:215: recipe for target 'bootload' failed
make: *** [bootload] Error 1
```
I am not sure if I need to add a pullup or pulldown on a pin like on the edge button 14 in order to flash the module or if I missed something in the setup guide, but it appears the python script is having trouble sending a "hello" to the Artemis board. I'd love to know if there is something I am missing in the setup of my toolchain or if this is a larger problem for the Artemis boards, and I can give you more information about my specific toolchain setup if anyone needs.

**Comment by oclyke** [comment]
@ComputerAided  your baud rate is set to 921600 in the upload tool's command line arguments. This is correct for the Edge but all the Artemis boards ship with an 115200 Secure Bootloader for better failsafe action. 

Try using ```/home/***/AmbiqSuite-Rel2.1.0/boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py -b 115200/dev/ttyUSB0  -r 1 -f bin/main_nonsecure_wire.bin -i 6``` instead.

You should be able to find the relevant part of the makefile easily. Please let us know how that goes.

**Comment by ComputerAided** [comment]
@oclyke I tried setting the baud rate to 115200 in the makefile, but I am still getting the same error.

```bash
/home/***/AmbiqSuite-Rel2.1.0/boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py -b 115200 /dev/ttyUSB0  -r 1 -f bin/main_nonsecure_wire.bin -i 6
Connecting with Corvette over serial port /dev/ttyUSB0...
Sending Hello.
No response for command 0x00000000
Traceback (most recent call last):
  File "/home/***/AmbiqSuite-Rel2.1.0/boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py", line 341, in <module>
    main()
  File "/home/***/AmbiqSuite-Rel2.1.0/boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py", line 42, in main
    connect_device(ser)
  File "/home/***/AmbiqSuite-Rel2.1.0/boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py", line 61, in connect_device
    response = send_command(hello, 88, ser)
  File "/home/***/AmbiqSuite-Rel2.1.0/boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py", line 238, in send_command
    raise NoResponseError
__main__.NoResponseError
Makefile:215: recipe for target 'bootload' failed
make: *** [bootload] Error 1
```

I also was able to install Arduino with the Apollo3 addon. I used the Ambiq Secure Bootloader at 115200 baud to try and upload the Artemis Example1_Blink sketch, and I am guessing I am getting the same error. 
```
/home/***/.arduino15/packages/SparkFun/hardware/apollo3/1.0.2/tools/ambiq/linux/ambiq_bin2board --bin /tmp/arduino_build_972278/Example1_Blink.ino.bin --load-address-blob 0x20000 --magic-num 0xCB -o /tmp/arduino_build_972278/Example1_Blink.ino --version 0x0 --load-address-wired 0xC000 -i 6 --options 0x1 -b 115200 -port /dev/ttyUSB0 -r 2 -v 
Header Size =  0x80
original app_size  0x1cf0 ( 7408 )
load_address  0xc000 ( 49152 )
app_size  0x1cf0 ( 7408 )
w0 = 0xcb001d70
Security Value  0x10
w2 =  0x10008080
addrWord =  0xc000
versionKeyWord =  0x0
child0/feature =  0xffffffff
child1 =  0xffffffff
crc =   0x45bcf34a
Writing to file  /tmp/arduino_build_972278/Example1_Blink.ino_OTA_blob.bin
testing: /tmp/arduino_build_972278/Example1_Blink.ino_OTA_blob.bin
Header Size =  0x60
app_size  0x1d70 ( 7536 )
Writing to file  /tmp/arduino_build_972278/Example1_Blink.ino_Wired_OTA_blob.bin
Image from  0x0  to  0x1d70  will be loaded at 0x20000
Connecting over serial port /dev/ttyUSB0...
Sending Hello.
No response for command 0x00000000
Failed to respond
Fail
Sending Hello.
No response for command 0x00000000
Failed to respond
Fail
Sending Hello.
No response for command 0x00000000
Failed to respond
Fail
Tries = 3
Upload failed
```

I read in this [forum thread](https://forum.sparkfun.com/viewtopic.php?f=153&t=49965) that it may have something to do with the default CH341 driver that isn't allowing the board to be properly reset, but I tried to use the patched CH340 driver from juliagoda/CH341SER. I noticed it still appeared as a CH341 when running `lsmod` and using the `rmmod ch341` would only work until I unplugged the board and plugged it in again.

I wish I was able to probe the BOOTLOAD and RESET lines, but looking at the board file makes it look like there is no good way to probe them to make sure pins are being driven as they should be. I also have an FTDI Serial adapter lying around and could try to use it, but I'm not sure I'd be able to make all of the connections I'd need to make.

I'm not sure if it is anything related to sparkfun/Arduino_Apollo3#21 that the board is failing to respond, but let me know if there is anything I need to try out. Hope this helps!

**Comment by oclyke** [comment]
Hey @ComputerAided this is interesting... at 115200 baud I would not expect to see the driver issues appear. Do you know what is happening on the Serial (UART0) lines? I wonder if this might be related to the issue we see here: https://forum.sparkfun.com/viewtopic.php?f=164&t=50373&p=206260#p206260

I've been working on bootloader problems for a while now - I think the Arduino core version that you are using defaults to using the Ambiq Secure Bootloader which I think has a vulnerability to excess UART communications. I have a hunch that this *might* be able to be fixed just by modifying the uploader Python script (maybe clear a buffer at just the right time or something?) I won't be able to work on that until after I make some progress on BLE however. If you feel up to it I'd suggest scoping the UART lines during upload (with the ASB) and following along in their Python script (or equivalently my 'artemis_bin2board.py' in the Arduino core tools->ambiq directory) to see where/why that error occurs.


If you were able to upload code then you could upload the improved (version 3) SparkFun Variable Loader (SVL) and then use that. (It is available in the Arduino Core v1.0.4 that was just released).

**Comment by UFS-desgin** [comment]
When is Sparkfun expecting to release the Artemis ATP BSP files? My area of interest is using the BLE function of Artemis. With Artemis Arduino is is one BLE example. Looking at the apollo3_evb examples folder there are over 10 BLE projects. Would I be better to purchase this board?

**Comment by oclyke** [comment]
@UFS-desgin this repo is deprecated. There are BSP files for all our boards here:
https://github.com/sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs

We also provide the AmbiqSuite SDK Rel2.2.0 with our BSPs included here:
https://github.com/sparkfun/AmbiqSuiteSDK

And now there is a really convenient way to set up a development environment with Docker here:
https://github.com/sparkfun/artemis_dev_platform

Each one build off the previous offerings - for example the Docker environment includes the AmbiqSuiteSDK which includes the BSPs. So the easiest way by far is to just use the Docker environment
