### ISSUE TITLE
spi_testing_in_c

### ISSUE THREAD

**Issue by RicoFio** [sparkfun/SparkFun_Edge_BSP#12]
### Expected Behaviour: 

with a make clean && make boatload, the program should be flashed onto the Edge Dev Board.

### Experienced Behaviour:

**user:gcc user$** make clean
Cleaning...
**user:gcc user$** make bootload
 Compiling gcc ../src/main.c
../src/main.c: In function 'main':
../src/main.c:127:5: warning: implicit declaration of function 'memset' [-Wimplicit-function-declaration]
     memset((void*)&iomaster_pin_config, 0x00, sizeof(am_hal_gpio_pincfg_t));
     ^~~~~~
../src/main.c:127:5: warning: incompatible implicit declaration of built-in function 'memset'
../src/main.c:127:5: note: include '<string.h>' or provide a declaration of 'memset'
../src/main.c:18:1:
+#include <string.h>
 
../src/main.c:127:5:
     memset((void*)&iomaster_pin_config, 0x00, sizeof(am_hal_gpio_pincfg_t));
     ^~~~~~
 Compiling gcc ../../../../../devices/am_devices_led.c
 Compiling gcc ../../../../../utils/am_util_delay.c
 Compiling gcc ../../../../../utils/am_util_faultisr.c
 Compiling gcc ../../../../../utils/am_util_stdio.c
 Compiling gcc startup_gcc.c
 Linking gcc bin/spi_test.axf
**/usr/local/bin/gcc-arm-none-eabi-8-2018-q4-major/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld: read in flex scanner failed
collect2: error: ld returned 1 exit status
make: *** [bin/spi_test.axf] Error 1**

### Environment
Mac OS Mojave 10.14.5 (18F132)

**user:gcc user$** gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

### Request

How can this be fixed? Is anyone experiencing a similar issue?

**Comment by oclyke** [comment]
Hi @RicoFio I can confirm these compilation issues. 

We are focusing our efforts on the Apollo3 Arduino Core (https://github.com/sparkfun/Arduino_Apollo3) and there you can find better examples of SPI usage.


In the meantime here's a really quick solution: 

- Add ```#include <string.h>``` to includes at the top of main.c
- Replace ```strlcpy((char*)tx_buffer, (const char*)tx_msg, TX_SIZE);``` with 

```
    for(uint32_t indi = 0; indi < (TX_SIZE-1); indi++){
        if( *(tx_msg + indi) == '\0' ){
            break;
        }
        tx_buffer[indi + 1] = '\0';
    }
```
