### ISSUE TITLE
make bootload does not work

### ISSUE THREAD

**Issue by genivia-inc** [sparkfun/SparkFun_Edge_BSP#2]
Some issues that I had on Mac OS X: `make boatload` does not work:

    make: *** No rule to make target `bootload'.  Stop.

But `make all` works fine, though it does not flash. Second, I also had to change the Makefile `SWROOT` definition because `cygpath` isn't a portable command. Third, I used a simple trick to get my SparkFun serial port without editing Makefiles by `$(shell ls /dev/tty.wchusb*)` which works on Mac OS X and a similar trick probably works for Linux too:

    #### Bootloader Configuration
    SERIAL_PORT ?= $(shell ls /dev/tty.wchusb*)

    # All makefiles use this to find the top level directory.
    SWROOT ?= ../../../..

    # Include rules for building generic examples.
    include $(SWROOT)/makedefs/example.mk

Hope this helps.

**Comment by oclyke** [comment]
@genivia-inc thanks for these recommendations. To get a little more info can you tell me which Makefile you are using to build the project? We've been running make from within the ```example/gcc``` directory, and those Makefiles should have a ```bootload``` target. 

I'll look into the ```SWROOT``` and ```SERIAL_PORT``` changes too.

**Comment by genivia-inc** [comment]
I got stuck at this step trying example `AmbiqSuite-Rel2.0.0/boards/SparkFun_Edge_BSP/examples/example1_edge_test` by changing the Makefile using the documentation at https://learn.sparkfun.com/tutorials/using-sparkfun-edge-board-with-ambiq-apollo3-sdk/example-applications

The documentation mentions `edge_test` and I assume it is `example1_edge_test`. I got the latest files downloaded yesterday. I checked `AmbiqSuite-Rel2.0.0/makedefs/example.mk` which does not have a rule for `bootload` nor imports one. Also, `make` also won't work because its trying to build `config.ini` without success because there is no `wildcard` command (at least not on a Mac). But `make all` works, but this won't start the bootload process. So I got `AmbiqSuite-Rel2.0.0/boards/SparkFun_Edge_BSP/examples/example1_edge_test/gcc/bin/example1_edge_test.bin` and can figure out how to bootload it manually, though it would be better if the documentation is complete.

Hope this helps.

**Comment by oclyke** [comment]
Sorry for the confusion, what I meant by ```example/gcc``` is that within our Board Support Package (BSP) folder there are several examples. When 'installed' in the correct location you should have the path ```AMB_ROOT/boards/SparkFun_Edge_BSP/examples/exampleN_examplename/gcc```. You will build and bootload the example from that directory i.e.

```
cd AMB_ROOT/boards/SparkFun_Edge_BSP/examples/exampleN_examplename/gcc
make clean
make bootload
```

Some other snag points include:
* an error in the SDK from Ambiq (Rel2.0.0 at least) where the file ```keys_info0.py``` should be renamed to just ```keys_info.py``` (located under ```AMB_ROOT/tools/apollo3_scripts```)
* the need to make sure you install pyserial and pycryptodome to the correct instance of Python (3.x) that will be used by the scripts

Please let me know if that helps at all

**Comment by genivia-inc** [comment]
Aha! Somehow I missed that `make bootload` should be executed within the `gcc` directory and the Makefile there should be updated instead of the Makefile in `example1_edge_test`.

I see that `pycryptodome` should be installed whereas the site https://codelabs.developers.google.com/codelabs/sparkfun-tensorflow/#2 mentions `pycrypto` instead of `pycryptodome`. So I removed `pycrypto` and installed `pycryptodome`. Perhaps someone should update that site to reflect this, because `pycryptodome` replaces `pycrypto` with Python 3. I already have `pyserial` installed.

**Comment by genivia-inc** [comment]
A problem I'm running into with `make bootload` is that the baud rate setting is too high:
~~~
Writing to file  bin/main_nonsecure_wire.bin
Image from  0x0  to  0x48fc  will be loaded at 0x20000
../../../bsp/tools/uart_wired_update_sparkfun.py -b 921600 /dev/tty.wchusbserial1410 -r 1 -f bin/main_nonsecure_wire.bin -i 6
Connecting with Corvette over serial port /dev/tty.wchusbserial1410...
Sending Hello.
No response for command 0x00000000
Traceback (most recent call last):
  File "../../../bsp/tools/uart_wired_update_sparkfun.py", line 341, in <module>
    main()
  File "../../../bsp/tools/uart_wired_update_sparkfun.py", line 42, in main
    connect_device(ser)
  File "../../../bsp/tools/uart_wired_update_sparkfun.py", line 61, in connect_device
    response = send_command(hello, 88, ser)
  File "../../../bsp/tools/uart_wired_update_sparkfun.py", line 238, in send_command
    raise NoResponseError
__main__.NoResponseError
make: *** [bootload] Error 1
~~~
I believe it should be 115200 as explained here: https://codelabs.developers.google.com/codelabs/sparkfun-tensorflow/#3
~~~
python3 tensorflow/lite/experimental/micro/tools/make/downloads/AmbiqSuite-Rel2.0.0/tools/apollo3_scripts/uart_wired_update.py -b 115200 DEVICENAME -r 1 -f main_nonsecure_wire.bin -I 6
~~~
which works for me.

**Comment by oclyke** [comment]
You're right about that, it slipped my mind earlier. See the first round of HW went to the TensorFlow summit with the bootloader configured for 115200 as you have noticed. The boards that we are selling on our website now have been upgraded to the faster baud rate. It is perfectly fine to simply make that modification. To use the full speed bootloader it needs to be enabled onboard using a debugger such as a SEGGER J-Link. To do that you would use the ```create_info0.py``` script with the desired baud rate as a switch. Then you would use the debugger to flash the resulting ```info0.bin``` file onto the board.

Thanks again for raising these concerns, I hope others will be able to find it helpful.

**Comment by genivia-inc** [comment]
Great to hear it can work with higher baud rates, which makes SparkFun Edge even more useful.
