### ISSUE TITLE
Flashing App with JLink

### ISSUE THREAD

**Issue by jwinarske** [sparkfun/SparkFun_Edge_BSP#9]
I am able to Flash a custom app via UART.  This works fine.  The sequence I'm using is:
```
~/Documents/AmbiqSuite-Rel2.1.0/tools/apollo3_scripts/create_cust_image_blob.py --bin ref_app.bin --load-address 0xC000 --magic-num 0xCB -o main_nonsecure_ota --version 0x0
~/Documents/AmbiqSuite-Rel2.1.0/tools/apollo3_scripts/create_cust_wireupdate_blob.py --load-address 0x20000 --bin main_nonsecure_ota.bin -i 6 -o main_nonsecure_wire --options 0x1
~/Documents/AmbiqSuite-Rel2.1.0/boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py -b 921600 /dev/ttyUSB0 -r 1 -f main_nonsecure_wire.bin -i 6

```
What is the sequence to flash a custom app via JLink, such that the bootloader is happy?

**Comment by jwinarske** [comment]
AMSDKGS - Section 5.3 Programming Images with JFlashLite...

The above section appears to only work properly after I have Flashed a custom app via UART.  I suspect there is a missing dependency for this.  As flashing to 0xC000 prior would end up in a tight loop in the bootloader somewhere.

**Comment by jwinarske** [comment]
Actually, it looks like the issue is my stack pointer setting.  When setting the stack pointer to 0x10014000, it works.  When setting it to the end of SRAM; 0x10060000, it fails.  I was setting it to the end of SRAM.

What is the usable SRAM range for "apps" on Apollo3?

**Comment by jwinarske** [comment]
I submitted a ticket with Ambiq.

**Comment by oclyke** [comment]
@jwinarske Thanks for your notes here. I've noticed some peculiarities with the example applications -- for example they use a statically allocated stack area and do not provide the necessary symbols to grow a heap.

Eventually I want to get more familiar with what they are doing with the ultimate goal of moving toward a more typical "stack grows toward heap" setup. For now, however, it is relatively low on priorities. 

If you find out more I'd certainly like to hear about it.

**Comment by jwinarske** [comment]
I received a preliminary response I need to follow-up on.  The statement was the part may only have some of it's SRAM powered on by default.  To support low power.  I need to dig into what the particular chicken bits are...

You may be interested, I'm adding support for Apollo 3 in this repo: https://github.com/ckormanyos/real-time-cpp

**Comment by jwinarske** [comment]
The Main SRAM (TCM) is always powered on.  The main SRAM turns on and off for power savings.  Which is why the lower section of TCM is used for the stack in the examples.

**Comment by oclyke** [comment]
Good to know for when we start monkeying around in there! Thanks!
